name: WebDriverIO Mobile Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Executa todos os dias às 2h da manhã
    - cron: '0 2 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        api-level: [35]
        target: [google_apis]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Install Appium
      run: |
        npm install -g appium
        appium driver list --installed || appium driver install uiautomator2
    
    - name: Download Android App
      run: |
        mkdir -p apps/android
        curl -L -o apps/android/app-debug.apk https://github.com/webdriverio/native-demo-app/releases/download/v0.4.0/Android-NativeDemoApp-0.4.0.apk
    
    - name: Enable KVM group perms
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
    
    - name: Run tests on Android Emulator
      id: emulator_tests
      continue-on-error: true
      uses: reactivecircus/android-emulator-runner@v2
      timeout-minutes: 10
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        emulator-options: -no-snapshot-save -no-snapshot-load -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -wipe-data
        disable-animations: true
        script: npm test
    
    - name: Force cleanup emulator processes
      if: always()
      run: |
        pkill -9 -f qemu-system || true
        pkill -9 -f emulator || true
        pkill -9 -f adb || true
        pkill -9 -f appium || true
        
    - name: Check test results
      if: always()
      run: |
        if [ -f "allure-results" ]; then
          echo "✅ Tests executed successfully"
          exit 0
        else
          echo "❌ Tests failed"
          exit 1
        fi
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-api-${{ matrix.api-level }}
        path: |
          allure-results/
          screenshots/
    
    - name: Upload screenshots on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: screenshots-api-${{ matrix.api-level }}
        path: screenshots/
